const http=require('http');
const fs=require('fs');
const path=require('path');
const {exec}=require('child_process');
const https=require('https');
const ROOT=__dirname, PUBLIC=path.join(ROOT,'public'), DATA=path.join(ROOT,'data.json'), BACKUPS=path.join(ROOT,'backups');
function loadEnv(){
 const file=path.join(ROOT,'.env'); if(!fs.existsSync(file))return;
 for(const line of fs.readFileSync(file,'utf8').split(/\r?\n/)){const t=line.trim();if(!t||t.startsWith('#'))continue;const i=t.indexOf('=');if(i<1)continue;const k=t.slice(0,i).trim(),v=t.slice(i+1).trim();if(!process.env[k])process.env[k]=v;}
}
loadEnv();
function stripeRequest(method,endpoint,params){
 return new Promise((resolve,reject)=>{
  const body=new URLSearchParams(params||{}).toString();
  const req=https.request({hostname:'api.stripe.com',path:'/v1'+endpoint,method,headers:{Authorization:'Bearer '+(process.env.STRIPE_SECRET_KEY||''),'Content-Type':'application/x-www-form-urlencoded','Content-Length':Buffer.byteLength(body)}},r=>{
   let chunks='';r.on('data',c=>chunks+=c);r.on('end',()=>{let j;try{j=JSON.parse(chunks)}catch{j={error:{message:chunks||'Resposta Stripe no vàlida'}}}if(r.statusCode>=200&&r.statusCode<300)resolve(j);else reject(new Error(j?.error?.message||'Error Stripe'));});
  });req.on('error',reject);if(body)req.write(body);req.end();
 });
}
const PORT=Number(process.env.PORT||3210), HOST=process.env.HOST||'127.0.0.1';
function send(res,status,body,type='application/json; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(typeof body==='string'?body:JSON.stringify(body));}
function readData(){try{return JSON.parse(fs.readFileSync(DATA,'utf8'));}catch(e){throw new Error('No es pot llegir data.json: '+e.message)}}
function backupCurrent(){if(!fs.existsSync(BACKUPS))fs.mkdirSync(BACKUPS,{recursive:true});if(fs.existsSync(DATA)){const stamp=new Date().toISOString().replace(/[:.]/g,'-');fs.copyFileSync(DATA,path.join(BACKUPS,`data_${stamp}.json`));const files=fs.readdirSync(BACKUPS).filter(x=>x.endsWith('.json')).sort().reverse();files.slice(30).forEach(f=>fs.unlinkSync(path.join(BACKUPS,f)));}}
function writeData(data){data.updatedAt=new Date().toISOString();backupCurrent();const tmp=DATA+'.tmp';fs.writeFileSync(tmp,JSON.stringify(data,null,2),'utf8');fs.renameSync(tmp,DATA);return data;}
function bodyJson(req,limit=25*1024*1024){return new Promise((resolve,reject)=>{let chunks=[],n=0;req.on('data',c=>{n+=c.length;if(n>limit){reject(new Error('Fitxer massa gran'));req.destroy();return}chunks.push(c)});req.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}'))}catch(e){reject(new Error('JSON no vàlid'))}});req.on('error',reject);});}
function safeStatic(urlPath){let p=decodeURIComponent(urlPath.split('?')[0]);if(p==='/'||p==='')p='/index.html';const full=path.normalize(path.join(PUBLIC,p));if(!full.startsWith(PUBLIC))return null;return full;}
function mime(file){const ext=path.extname(file).toLowerCase();return ({'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.wasm':'application/wasm','.gz':'application/gzip','.txt':'text/plain; charset=utf-8'}[ext]||'application/octet-stream');}
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function menuPrice(x){if(Number.isFinite(Number(x.reservationPrice)))return Number(x.reservationPrice);if(Number.isFinite(Number(x.priceNumeric)))return Number(x.priceNumeric);const v=String(x.price||'').replace(',','.').match(/\d+(?:\.\d+)?/);return v?Number(v[0]):0;}
function nextProductCode(data,family,reserved=[]){const def=(data.config?.families||[]).find(f=>f.name===family)||{prefix:'ALT'};let max=0;[...(data.products||[]),...reserved].forEach(p=>{const m=String(p.code||'').match(new RegExp('^'+def.prefix+'-(\\d+)$','i'));if(m)max=Math.max(max,Number(m[1]));});return def.prefix+'-'+String(max+1).padStart(3,'0');}
function haversine(lat1,lon1,lat2,lon2){const R=6371000,toRad=x=>x*Math.PI/180;const dlat=toRad(lat2-lat1),dlon=toRad(lon2-lon1);const a=Math.sin(dlat/2)**2+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dlon/2)**2;return 2*R*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
const server=http.createServer(async(req,res)=>{try{
 const u=new URL(req.url,`http://${req.headers.host||HOST}`);const p=u.pathname;
 if(p==='/api/health')return send(res,200,{ok:true});
 if(p==='/api/state'&&req.method==='GET')return send(res,200,readData());
 if(p==='/api/state'&&(req.method==='POST'||req.method==='PUT')){const d=await bodyJson(req);if(!d||typeof d!=='object')return send(res,400,{error:'Dades no vàlides'});return send(res,200,{ok:true,state:writeData(d)});}
 if(p==='/api/control-state'&&req.method==='GET')return send(res,200,readData().controlNormatiu||{empresa:{},records:{}});
 if(p==='/api/control-state'&&req.method==='POST'){const c=await bodyJson(req);const d=readData();d.controlNormatiu=c;writeData(d);return send(res,200,{ok:true});}
 if(p==='/api/products-bulk'&&req.method==='POST'){const payload=await bodyJson(req),rows=Array.isArray(payload.rows)?payload.rows:[];const d=readData();d.products=d.products||[];let created=0,updated=0,skipped=0;const reserved=[];for(const row of rows){const name=String(row.name||'').trim();if(!name){skipped++;continue}let found=d.products.find(x=>norm(x.name)===norm(name));if(found){found.price=Number(row.price||0);found.family=row.family||found.family||'Altres';found.unit=row.unit||found.unit||'unitat';found.subfamily=row.subfamily||found.subfamily||'';found.active=true;updated++;continue}const family=row.family||'Altres';const code=row.code||nextProductCode(d,family,reserved);const prod={id:'prod_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7),code,supplierCode:row.supplierCode||'',name,family,subfamily:row.subfamily||'',unit:row.unit||'unitat',price:Number(row.price||0),stock:0,min:0,supplierId:row.supplierId||'',location:'',notes:'Creat des de l’OCR',active:true};d.products.push(prod);reserved.push(prod);created++;}writeData(d);return send(res,200,{ok:true,created,updated,skipped});}
 if(p==='/api/punch'&&req.method==='POST'){const x=await bodyJson(req),d=readData();d.punches=d.punches||[];const emp=(d.employees||[]).find(e=>String(e.code)===String(x.code));if(!emp)return send(res,404,{error:'Codi d’empleat no trobat'});const gps=d.company?.gps||{};let distance=null,status='GPS NO DISPONIBLE';if(Number.isFinite(Number(x.lat))&&Number.isFinite(Number(x.lng))&&Number.isFinite(Number(gps.lat))&&Number.isFinite(Number(gps.lng))){distance=haversine(Number(x.lat),Number(x.lng),Number(gps.lat),Number(gps.lng));status=distance<=Number(gps.radius||60)?'DINS DE ZONA':'FORA DE ZONA';}const punch={id:'punch_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,6),employeeId:emp.id,employeeCode:emp.code,employeeName:emp.name,type:x.type,dateTime:new Date().toISOString(),lat:x.lat??null,lng:x.lng??null,accuracy:x.accuracy??null,distance:distance===null?null:Math.round(distance),status};d.punches.push(punch);writeData(d);return send(res,200,{ok:true,punch});}
 if(p==='/api/reservation-config'&&req.method==='GET'){const d=readData(),cfg=d.reservationConfig||{},menus=(d.documents||[]).filter(x=>x.type==='Menú'&&x.publishReservations===true).map(x=>({id:x.id,title:x.title,subtitle:x.subtitle||'',price:menuPrice(x),depositType:x.depositType||'fixed',depositValue:Number(x.depositValue||0),notes:x.publicReservationNotes||x.notes||'',attachment:x.reservationAttachment||''}));return send(res,200,{company:{name:d.company?.name||'Casa Mestres',phone:d.company?.phone||'',email:d.company?.email||'',logo:d.company?.logo||''},config:{maxPax:Number(cfg.maxPax||10),groupPhone:cfg.groupPhone||d.company?.phone||'',cancellationPolicy:cfg.cancellationPolicy||'',stripeEnabled:!!process.env.STRIPE_SECRET_KEY,currency:cfg.currency||'EUR'},menus});}
 if(p==='/api/reservations'&&req.method==='POST'){const x=await bodyJson(req),d=readData();d.reservations=d.reservations||[];const cfg=d.reservationConfig||{},maxPax=Number(cfg.maxPax||10),pax=Number(x.pax||0);if(!x.date||!x.time||!String(x.name||'').trim()||!String(x.phone||'').trim())return send(res,400,{error:'Falten dades obligatòries'});if(!Number.isInteger(pax)||pax<1||pax>maxPax)return send(res,400,{error:`Per a més de ${maxPax} persones cal fer reserva de grup i contactar amb el restaurant.`});const menu=(d.documents||[]).find(m=>m.id===x.menuId&&m.type==='Menú'&&m.publishReservations===true);if(!menu)return send(res,400,{error:'Menú no disponible'});const keyName=norm(x.name),dup=d.reservations.find(r=>r.date===x.date&&norm(r.name)===keyName&&!['cancel·lada','cancelled'].includes(norm(r.status)));if(dup)return send(res,409,{error:'Ja existeix una reserva amb aquest nom per aquest dia. Contacta amb el restaurant si necessites modificar-la.'});const price=menuPrice(menu),depositType=menu.depositType||'fixed',depositValue=Number(menu.depositValue||0),deposit=depositType==='percent'?price*pax*depositValue/100:pax*depositValue;const r={id:'res_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7),createdAt:new Date().toISOString(),date:x.date,time:x.time,pax,zone:x.zone||'Sala principal',name:String(x.name).trim(),phone:String(x.phone).trim(),email:String(x.email||'').trim(),menuId:menu.id,menuTitle:menu.title,menuPrice:price,depositType,depositValue,depositAmount:Math.round(deposit*100)/100,status:process.env.STRIPE_SECRET_KEY?'Pendent pagament':'Pendent Stripe',paymentStatus:'pendent',marketing:!!x.marketing,notes:String(x.notes||'').trim()};d.reservations.push(r);writeData(d);return send(res,200,{ok:true,reservation:r,stripeEnabled:!!process.env.STRIPE_SECRET_KEY,message:cfg.stripeEnabled?'Reserva creada. Falta completar el pagament Stripe.':'Reserva registrada en mode prova; Stripe encara no està activat.'});}
 if(p==='/api/stripe/confirm'&&req.method==='GET'){
  if(!process.env.STRIPE_SECRET_KEY)return send(res,400,{error:'Stripe no està configurat'});
  const sid=u.searchParams.get('session_id');if(!sid)return send(res,400,{error:'Falta session_id'});
  const session=await stripeRequest('GET','/checkout/sessions/'+encodeURIComponent(sid),{});
  const rid=session.metadata?.reservation_id;const d=readData();const r=(d.reservations||[]).find(x=>x.id===rid||x.stripeSessionId===sid);
  if(!r)return send(res,404,{error:'Reserva no trobada'});
  if(session.payment_status==='paid'){r.paymentStatus='pagat';r.status='Confirmada';r.paidAt=new Date().toISOString();r.stripeSessionId=sid;r.stripePaymentIntent=session.payment_intent||'';writeData(d);}
  return send(res,200,{ok:true,paid:session.payment_status==='paid',reservation:r});
 }
 if(p==='/api/restore'&&req.method==='POST'){const d=await bodyJson(req);if(!d.schema||!d.company)return send(res,400,{error:'La còpia no correspon a l’app consolidada'});writeData(d);return send(res,200,{ok:true});}
 if(p==='/api/backup'&&req.method==='GET'){const content=fs.readFileSync(DATA);res.writeHead(200,{'Content-Type':'application/json; charset=utf-8','Content-Disposition':`attachment; filename="CASA_MESTRES_BACKUP_${new Date().toISOString().slice(0,10)}.json"`});return res.end(content);}
 const f=safeStatic(p);if(!f||!fs.existsSync(f)||!fs.statSync(f).isFile())return send(res,404,'No trobat','text/plain; charset=utf-8');res.writeHead(200,{'Content-Type':mime(f),'Cache-Control':'no-cache'});fs.createReadStream(f).pipe(res);
 }catch(e){send(res,500,{error:e.message});}});
server.listen(PORT,HOST,()=>{const url=`http://${HOST}:${PORT}`;console.log(`CASA MESTRES APP CONSOLIDADA: ${url}`);if(process.platform==='win32'&&!process.env.NO_OPEN)setTimeout(()=>exec(`start "" "${url}"`),600);});
